# GPT-2 pretraining setup
{
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe-parallel-size": 1,
   "model-parallel-size": 1,
   "make_vocab_size_divisible_by": 1,

   # model settings
   "num-layers": 32,
   "hidden-size": 4096,
   "num-attention-heads": 32,
   "seq-length": 8192,
   "max-position-embeddings": 8192,
   "pos-emb": "rotary",
   "rotary-pct": 1,
   "no-weight-tying": true,
   "gpt-j-residual": false,
   "output-layer-parallelism": "column",
   "norm": "rmsnorm",
   "rms_norm_epsilon": 1.0e-6,

   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": false,
   "use_bias_in_norms": false,
   "use_bias_in_attn_linear": false,
   "mlp_type": "llama",
   "activation": "silu",
   "attention_config": [[["flash"], 32]],

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled-upper-triang-masked-softmax-fusion": false,
   "bias-gelu-fusion": false,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 5.0e-5,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 5.0e-6,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 4,
   "data-impl": "mmap",

   # activation checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
  #  "fp16": {
  #    "fp16": true,
  #    "enabled": true,
  #    "loss_scale": 0,
  #    "loss_scale_window": 1000,
  #    "hysteresis": 2,
  #    "min_loss_scale": 1
  #  },
  
   "bf16": {
      "enabled": true
    },

   # misc. training settings
   # train 10B tokens in total
   "train-iters": 9500,
   "lr-decay-iters": 9500,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.003,
   "checkpoint-factor": 1900,
   "eval-interval": 99999999,
   "eval-iters": 200,

   # logging
   "log-interval": 10,
   "steps_per_print": 10,
   "keep-last-n-checkpoints": 10,
   "wall_clock_breakdown": true,
}
